default: &default
  adapter: myql2
  pool: 5
  timeout: 5000
  username: root
  password:

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dev_db
  pool: 5
  username: root
  password: your_root_password
  # socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sample_sqlite3_test
  pool: 5
  username: root
  password: your_root_password
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sample_sqlite3_production
  pool: 5
  username: root
  password: your_root_password
  socket: /tmp/mysql.sock